import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../public/Public_Itens/Estilo/Default.css"
import NavBarMenu from "@/Componentes/NavMenu";
import Image from "next/image";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessao = await auth()
  // console.log(sessao)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider >
          <div className="Layout_Page">
            <NavBarMenu session={sessao} />
            {children}
          </div>
          <div className="Layout_Footer">
            <div className="Texto">
              <p>Artiszt 2024</p>
              <p>Versão 0.0.0/b.01</p>
              <p>by João Gabriel Caires Fernandes</p>
            </div>
            <div className="Image">
              <Image src="/Public_Itens/Imagens/Default_Site_Img/Macote-removebg-preview.png" width={'60'} height={'60'} alt="mascote artiszt" />
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
